// src/lib/theme/theme.config.ts

/**
 * Theme configuration for the application.
 * Maps semantic color names to CSS utility class equivalents.
 * Classes: bg-primary, text-primary, border-primary, icon-primary, etc.
 * Actual color values are defined via CSS custom properties in `src/app/globals.css`.
 */

export const themeConfig = {
  colors: {
    bg: {
      primary: 'bg-primary',
      secondary: 'bg-secondary',
      tertiary: 'bg-tertiary',
      quartiary: 'bg-quartiary',
      primaryHover: 'bg-primary-hover',
      secondaryHover: 'bg-secondary-hover',
      tertiaryHover: 'bg-tertiary-hover',
      quartiaryHover: 'bg-quartiary-hover',
      blackSolid: 'bg-black-solid',
      blackSolidHover: 'bg-black-solid-hover',
      disabled: 'bg-disabled',
      disabledAlt: 'bg-disabled-alt',
      accentPrimary: 'bg-accent-primary',
      accentPrimaryHover: 'bg-accent-primary-hover',
      accentSolid: 'bg-accent-solid',
      accentSolidHover: 'bg-accent-solid-hover',
      errorPrimary: 'bg-error-primary',
      errorPrimaryHover: 'bg-error-primary-hover',
      errorSecondary: 'bg-error-secondary',
      errorSecondaryHover: 'bg-error-secondary-hover',
      successPrimary: 'bg-success-primary',
      successPrimaryHover: 'bg-success-primary-hover',
      successSecondary: 'bg-success-secondary',
      successSecondaryHover: 'bg-success-secondary-hover',
      warningPrimary: 'bg-warning-primary',
      warningPrimaryHover: 'bg-warning-primary-hover',
      warningSecondary: 'bg-warning-secondary',
      warningSecondaryHover: 'bg-warning-secondary-hover',
      infoPrimary: 'bg-info-primary',
      infoPrimaryHover: 'bg-info-primary-hover',
      infoSecondary: 'bg-info-secondary',
      infoSecondaryHover: 'bg-info-secondary-hover',
      offerPrimary: 'bg-offer-primary',
      offerPrimaryHover: 'bg-offer-primary-hover',
      offerSecondary: 'bg-offer-secondary',
      offerSecondaryHover: 'bg-offer-secondary-hover',
      overlayAlphaPrimary: 'bg-overlay-alpha-primary',
      overlayAlphaSecondary: 'bg-overlay-alpha-secondary',
      overlayAlphaWhitePrimary: 'bg-overlay-alpha-white-primary',
      overlayAlphaWhiteSecondary: 'bg-overlay-alpha-white-secondary',
    },
    text: {
      primary: 'text-primary',
      secondary: 'text-secondary',
      tertiary: 'text-tertiary',
      primaryHover: 'text-primary-hover',
      secondaryHover: 'text-secondary-hover',
      tertiaryHover: 'text-tertiary-hover',
      disabled: 'text-disabled',
      disabledAlt: 'text-disabled-alt',
      placeholder: 'text-placeholder',
      white: 'text-white',
      onDarkColor: 'text-on-dark-color',
      accentPrimary: 'text-accent-primary',
      accentSecondary: 'text-accent-secondary',
      accentPrimaryHover: 'text-accent-primary-hover',
      accentSecondaryHover: 'text-accent-secondary-hover',
      errorPrimary: 'text-error-primary',
      errorSecondary: 'text-error-secondary',
      errorPrimaryHover: 'text-error-primary-hover',
      errorSecondaryHover: 'text-error-secondary-hover',
      successPrimary: 'text-success-primary',
      successSecondary: 'text-success-secondary',
      successPrimaryHover: 'text-success-primary-hover',
      successSecondaryHover: 'text-success-secondary-hover',
      warningPrimary: 'text-warning-primary',
      warningSecondary: 'text-warning-secondary',
      warningPrimaryHover: 'text-warning-primary-hover',
      warningSecondaryHover: 'text-warning-secondary-hover',
      infoPrimary: 'text-info-primary',
      infoSecondary: 'text-info-secondary',
      infoPrimaryHover: 'text-info-primary-hover',
      infoSecondaryHover: 'text-info-secondary-hover',
      offerPrimary: 'text-offer-primary',
      offerSecondary: 'text-offer-secondary',
      offerPrimaryHover: 'text-offer-primary-hover',
      offerSecondaryHover: 'text-offer-secondary-hover',
    },
    icon: {
      primary: 'icon-primary',
      secondary: 'icon-secondary',
      tertiary: 'icon-tertiary',
      primaryHover: 'icon-primary-hover',
      secondaryHover: 'icon-secondary-hover',
      tertiaryHover: 'icon-tertiary-hover',
      disabled: 'icon-disabled',
      disabledAlt: 'icon-disabled-alt',
      placeholder: 'icon-placeholder',
      white: 'icon-white',
      onDarkColor: 'icon-on-dark-color',
      accentPrimary: 'icon-accent-primary',
      accentSecondary: 'icon-accent-secondary',
      accentPrimaryHover: 'icon-accent-primary-hover',
      accentSecondaryHover: 'icon-accent-secondary-hover',
      errorPrimary: 'icon-error-primary',
      errorSecondary: 'icon-error-secondary',
      errorPrimaryHover: 'icon-error-primary-hover',
      errorSecondaryHover: 'icon-error-secondary-hover',
      successPrimary: 'icon-success-primary',
      successSecondary: 'icon-success-secondary',
      successPrimaryHover: 'icon-success-primary-hover',
      successSecondaryHover: 'icon-success-secondary-hover',
      warningPrimary: 'icon-warning-primary',
      warningSecondary: 'icon-warning-secondary',
      warningPrimaryHover: 'icon-warning-primary-hover',
      warningSecondaryHover: 'icon-warning-secondary-hover',
      infoPrimary: 'icon-info-primary',
      infoSecondary: 'icon-info-secondary',
      infoPrimaryHover: 'icon-info-primary-hover',
      infoSecondaryHover: 'icon-info-secondary-hover',
      offerPrimary: 'icon-offer-primary',
      offerSecondary: 'icon-offer-secondary',
      offerPrimaryHover: 'icon-offer-primary-hover',
      offerSecondaryHover: 'icon-offer-secondary-hover',
    },
    border: {
      primary: 'border-primary',
      secondary: 'border-secondary',
      tertiary: 'border-tertiary',
      primarySolid: 'border-primary-solid',
      disabled: 'border-disabled',
      disabledAlt: 'border-disabled-alt',
      accentPrimary: 'border-accent-primary',
      accentSecondary: 'border-accent-secondary',
      errorPrimary: 'border-error-primary',
      errorSecondary: 'border-error-secondary',
      successPrimary: 'border-success-primary',
      successSecondary: 'border-success-secondary',
      warningPrimary: 'border-warning-primary',
      warningSecondary: 'border-warning-secondary',
      infoPrimary: 'border-info-primary',
      infoSecondary: 'border-info-secondary',
      offerPrimary: 'border-offer-primary',
      offerSecondary: 'border-offer-secondary',
    }
  }
};
