import type { ConfettiPiece } from "./types";

const CONFETTI_PIECES: ConfettiPiece[] = [
  {
    id: 1,
    top: "4%",
    left: "6%",
    color: "#f59e0b",
    rotation: 20,
    size: 10,
    delay: 0,
  },
  {
    id: 2,
    top: "9%",
    left: "13%",
    color: "#ef4444",
    rotation: -15,
    size: 8,
    delay: 0.4,
  },
  {
    id: 3,
    top: "3%",
    left: "24%",
    color: "#38bdf8",
    rotation: 45,
    size: 9,
    delay: 0.8,
  },
  {
    id: 4,
    top: "14%",
    left: "33%",
    color: "#fde68a",
    rotation: -30,
    size: 7,
    delay: 1.2,
  },
  {
    id: 5,
    top: "6%",
    left: "44%",
    color: "#f97316",
    rotation: 10,
    size: 8,
    delay: 0.2,
  },
  {
    id: 6,
    top: "11%",
    left: "55%",
    color: "#ec4899",
    rotation: -20,
    size: 9,
    delay: 1.6,
  },
  {
    id: 7,
    top: "3%",
    left: "64%",
    color: "#38bdf8",
    rotation: 35,
    size: 8,
    delay: 0.6,
  },
  {
    id: 8,
    top: "9%",
    left: "74%",
    color: "#f59e0b",
    rotation: -10,
    size: 10,
    delay: 1.0,
  },
  {
    id: 9,
    top: "5%",
    left: "85%",
    color: "#ef4444",
    rotation: 25,
    size: 8,
    delay: 1.4,
  },
  {
    id: 10,
    top: "15%",
    left: "93%",
    color: "#fde68a",
    rotation: -25,
    size: 9,
    delay: 0.3,
  },
  {
    id: 11,
    top: "22%",
    left: "3%",
    color: "#ec4899",
    rotation: 15,
    size: 9,
    delay: 1.8,
  },
  {
    id: 12,
    top: "30%",
    left: "9%",
    color: "#f97316",
    rotation: -35,
    size: 7,
    delay: 0.5,
  },
  {
    id: 13,
    top: "26%",
    left: "94%",
    color: "#38bdf8",
    rotation: 40,
    size: 8,
    delay: 0.9,
  },
  {
    id: 14,
    top: "34%",
    left: "89%",
    color: "#f59e0b",
    rotation: -18,
    size: 9,
    delay: 1.3,
  },
  {
    id: 15,
    top: "62%",
    left: "5%",
    color: "#ef4444",
    rotation: 22,
    size: 8,
    delay: 0.7,
  },
  {
    id: 16,
    top: "70%",
    left: "12%",
    color: "#fde68a",
    rotation: -28,
    size: 9,
    delay: 1.5,
  },
  {
    id: 17,
    top: "65%",
    left: "20%",
    color: "#38bdf8",
    rotation: 12,
    size: 7,
    delay: 0.1,
  },
  {
    id: 18,
    top: "58%",
    left: "95%",
    color: "#ec4899",
    rotation: -22,
    size: 9,
    delay: 1.1,
  },
  {
    id: 19,
    top: "68%",
    left: "88%",
    color: "#f97316",
    rotation: 30,
    size: 8,
    delay: 1.7,
  },
  {
    id: 20,
    top: "76%",
    left: "93%",
    color: "#f59e0b",
    rotation: -12,
    size: 9,
    delay: 0.4,
  },
  {
    id: 21,
    top: "88%",
    left: "8%",
    color: "#ef4444",
    rotation: 18,
    size: 8,
    delay: 0.9,
  },
  {
    id: 22,
    top: "92%",
    left: "18%",
    color: "#38bdf8",
    rotation: -32,
    size: 9,
    delay: 1.2,
  },
  {
    id: 23,
    top: "85%",
    left: "30%",
    color: "#fde68a",
    rotation: 24,
    size: 7,
    delay: 0.6,
  },
  {
    id: 24,
    top: "90%",
    left: "70%",
    color: "#ec4899",
    rotation: -16,
    size: 8,
    delay: 1.6,
  },
  {
    id: 25,
    top: "86%",
    left: "80%",
    color: "#f97316",
    rotation: 28,
    size: 9,
    delay: 0.2,
  },
  {
    id: 26,
    top: "94%",
    left: "90%",
    color: "#f59e0b",
    rotation: -20,
    size: 8,
    delay: 1.0,
  },
];

export default function ConfettiBackground() {
  return (
    <div className="pointer-events-none absolute inset-0 overflow-hidden">
      {CONFETTI_PIECES.map((piece) => (
        <span
          key={piece.id}
          className="absolute rounded-sm opacity-80"
          style={{
            top: piece.top,
            left: piece.left,
            width: piece.size,
            height: piece.size * 2.2,
            backgroundColor: piece.color,
            transform: `rotate(${piece.rotation}deg)`,
            animation: `confetti-drift 4.5s ease-in-out ${piece.delay}s infinite`,
          }}
        />
      ))}
      <style>{`
        @keyframes confetti-drift {
          0%, 100% { transform: translateY(0) rotate(var(--r, 0deg)); }
          50% { transform: translateY(10px) rotate(calc(var(--r, 0deg) + 12deg)); }
        }
      `}</style>
    </div>
  );
}
